# Generated by Django 4.2.16 on 2026-03-19 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predicted_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('model_version', models.CharField(default='linear_v1', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='products.product')),
            ],
            options={
                'db_table': 'sales_forecasts',
                'ordering': ['forecast_date'],
                'unique_together': {('product', 'forecast_date', 'model_version')},
            },
        ),
    ]
