# Generated by Django 5.2.12 on 2026-04-01 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(max_length=20)),
                ('provider', models.CharField(choices=[('mtn', 'MTN MoMo'), ('vodafone', 'Vodafone Cash'), ('airteltigo', 'AirtelTigo Money')], max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pay_offline', 'Awaiting Customer Approval'), ('send_otp', 'Awaiting OTP'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paystack_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_transaction', to='sales.sale')),
            ],
            options={
                'db_table': 'paystack_transactions',
            },
        ),
    ]
