# Generated by Django 4.2.16 on 2026-03-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('void', 'Void'), ('refund', 'Refund'), ('price_change', 'Price Change'), ('stock_adjust', 'Stock Adjustment'), ('role_change', 'Role Change'), ('login_failed', 'Login Failed'), ('account_locked', 'Account Locked')], max_length=20)),
                ('entity_type', models.CharField(blank=True, default='', max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', max_length=50)),
                ('before_value', models.JSONField(blank=True, null=True)),
                ('after_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
